# Ver todos los estudiantes 
GET http://localhost:8000/api/app/estudiantes

# Crear un estudiante
POST http://localhost:8000/api/app/estudiantes
Content-Type: application/json

{
    "cod": 1234,
    "nombres": "Juan Perez",
    "email": "juan@test.com"
}

# Buscar un estudiante por su código
GET http://localhost:8000/api/app/estudiantes/1234 

# Ver todas las notas
GET http://localhost:8000/api/app/notas 

# Crear una nota
POST http://localhost:8000/api/app/notas
Content-Type: application/json

{
    "actividad": "Tarea 1",
    "nota": 4.5,
    "codEstudiante": 1234
}

# Ver notas de un estudiante
GET http://localhost:8000/api/app/notas/estudiante/1234    



